### index
GET http://127.0.0.1:6666



### API-info
GET http://127.0.0.1:6666/info



### cpcContent
POST http://127.0.0.1:6666/cpcContent
Content-Type: application/json

{
    "month": 5,
    "day": 4
}



### ccylContent
POST http://127.0.0.1:6666/ccylContent
